type Level = 'Core' | 'Pro';

export const SIGNAL_EXAMPLES: {
  title: string;
  category: string;
  app: string;
  description: string;
  api: string;
  level: Level;
  tags: string[];
  link: string;
  preview: string;
  wide?: boolean;
}[] = [
  {
    title: $localize`:@@recipe.01.title:Basic Form`,
    category: 'Form',
    app: $localize`:@@app.registrationForm:Registration Form`,
    description: $localize`:@@recipe.01.desc:Foundation form() with [formField] binding and live form state: touched, dirty, valid, and invalid.`,
    api: 'form()',
    level: 'Core',
    tags: ['form()', '[formField]', 'form state'],
    link: '01-basic-form/',
    preview: 'previews/01-basic-form.png',
  },
  {
    title: $localize`:@@recipe.02.title:Built-in Validations`,
    category: 'Validation',
    app: $localize`:@@app.registrationForm:Registration Form`,
    description: $localize`:@@recipe.02.desc:Built-in validators (required, email, minLength, pattern, min) with inline error messages and touched / dirty gating.`,
    api: 'required()',
    level: 'Core',
    tags: ['required', 'email', 'pattern'],
    link: '02-built-in-validations/',
    preview: 'previews/02-built-in-validations.png',
  },
  {
    title: $localize`:@@recipe.03.title:Cross-field Validation`,
    category: 'Validation',
    app: $localize`:@@app.confirmEmail:Confirm Email`,
    description: $localize`:@@recipe.03.desc:Validate one field against another across the form tree.`,
    api: 'validate()',
    level: 'Core',
    tags: ['validate()', 'apply()', 'schema()'],
    link: '03-cross-field-validation/',
    preview: 'previews/03-cross-field-validation.png',
  },
  {
    title: $localize`:@@recipe.04.title:Async Validation`,
    category: 'Async',
    app: $localize`:@@app.manageBooking:Manage Booking`,
    description: $localize`:@@recipe.04.desc:Debounced server checks with a pending state.`,
    api: 'validateHttp()',
    level: 'Pro',
    tags: ['validateHttp', 'debounce', 'pending'],
    link: '04-async-validation/',
    preview: 'previews/04-async-validation.png',
  },
  {
    title: $localize`:@@recipe.05.title:Array Validation`,
    category: 'Arrays',
    app: $localize`:@@app.pizzaMaker:Pizza Maker`,
    description: $localize`:@@recipe.05.desc:Validate every item in an array with applyEach and per-item rules.`,
    api: 'applyEach()',
    level: 'Pro',
    tags: ['applyEach', 'arrays', 'per-item'],
    link: '05-array-validation/',
    preview: 'previews/05-array-validation.png',
  },
  {
    title: $localize`:@@recipe.06.title:Custom Control`,
    category: 'Control',
    app: $localize`:@@app.pizzaMaker:Pizza Maker`,
    description: $localize`:@@recipe.06.desc:Build a custom FormValueControl the framework binds value and state to.`,
    api: 'FormValueControl',
    level: 'Pro',
    tags: ['FormValueControl', 'stepper'],
    link: '06-custom-control/',
    preview: 'previews/06-custom-control.png',
  },
  {
    title: $localize`:@@recipe.07.title:Debounced Input`,
    category: 'Async',
    app: $localize`:@@app.liveSearch:Live Search`,
    description: $localize`:@@recipe.07.desc:Delay model updates until the user pauses typing, then run a live fruit search.`,
    api: 'debounce()',
    level: 'Pro',
    tags: ['debounce', 'rxResource', 'live search'],
    link: '07-debounce-input/',
    preview: 'previews/07-debounce-input.png',
  },
  {
    title: $localize`:@@recipe.08.title:Conditional Validation`,
    category: 'Logic',
    app: $localize`:@@app.starlightCinema:Starlight Cinema`,
    description: $localize`:@@recipe.08.desc:Rules that switch on based on other field values.`,
    api: 'applyWhen()',
    level: 'Core',
    tags: ['applyWhen', 'applyWhenValue', 'when'],
    link: '08-conditional-validation/',
    preview: 'previews/08-conditional-validation.png',
  },
  {
    title: $localize`:@@recipe.09.title:Form Submission`,
    category: 'Submit',
    app: $localize`:@@app.signalsPopQuiz:Signals Pop Quiz`,
    description: $localize`:@@recipe.09.desc:Submit to a server, then route its errors back onto the fields.`,
    api: '[formRoot]',
    level: 'Core',
    tags: ['[formRoot]', 'submitting()', 'server errors'],
    link: '09-form-submission/',
    preview: 'previews/09-form-submission.png',
  },
  {
    title: $localize`:@@recipe.10.title:Dynamic Forms`,
    category: 'Dynamic',
    app: $localize`:@@app.roleBuilder:Role Builder`,
    description: $localize`:@@recipe.10.desc:Swap the form shape with the role: applyWhenValue narrows designer vs frontend, and contract vs fulltime.`,
    api: 'applyWhenValue()',
    level: 'Pro',
    tags: ['applyWhenValue', 'discriminated union', '[formRoot]'],
    link: '10-dynamic-forms/',
    preview: 'previews/10-dynamic-forms.png',
  },
  {
    title: $localize`:@@recipe.11.title:Zod Schema Validation`,
    category: 'Schema',
    app: $localize`:@@app.supportDesk:Support Desk`,
    description: $localize`:@@recipe.11.desc:Drive validation from a Zod schema, and swap that schema at runtime as the channel and severity change.`,
    api: 'validateStandardSchema()',
    level: 'Pro',
    tags: ['zod', 'standardSchema', 'reactive rules'],
    link: '11-zod-schema/',
    preview: 'previews/11-zod-schema.png',
    wide: true,
  },
  {
    title: $localize`:@@recipe.12.title:Field Metadata`,
    category: 'Metadata',
    app: $localize`:@@app.bookmarkHub:Bookmark Hub`,
    description: $localize`:@@recipe.12.desc:Attach reactive metadata to fields: custom keys, a reducer, built-in limits, and a managed link preview.`,
    api: 'metadata()',
    level: 'Pro',
    tags: ['metadata', 'createMetadataKey', 'MetadataReducer'],
    link: '12-field-metadata/',
    preview: 'previews/12-field-metadata.png',
  },
];
